[package]
name = "paqetz-dp"
description = "Datapath: raw IP_HDRINCL transmit, AF_PACKET receive, TUN device."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
libc = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
